#!/usr/bin/env python
"""Extract all unique Chinese/CJK characters from source and JSON files.
Outputs both font_codepoints.txt (human-readable) and src/core/font_codepoints.h (C++ header)."""
import os, sys

# Force UTF-8 output
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

chars = set()

for top_dir in ['src', 'resources']:
    for root, dirs, files in os.walk(top_dir):
        for fname in files:
            if not (fname.endswith('.cpp') or fname.endswith('.h') or fname.endswith('.json')):
                continue
            fpath = os.path.join(root, fname)
            try:
                with open(fpath, 'r', encoding='utf-8') as fh:
                    text = fh.read()
            except UnicodeDecodeError:
                try:
                    with open(fpath, 'r', encoding='gbk') as fh:
                        text = fh.read()
                except Exception:
                    continue
            except Exception:
                continue
            for ch in text:
                cp = ord(ch)
                if cp >= 0x2000:
                    chars.add(ch)

sorted_chars = sorted(chars)
total = len(sorted_chars)

# ASCII printable
ascii_cps = list(range(0x20, 0x7F))

# Essential extra symbols (must match C++ _extras in resource_manager.cpp)
extra = [
    0x00B7, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026,
    0x2190, 0x2191, 0x2192, 0x2193, 0x2194, 0x2208, 0x2260, 0x2265,
    0x2500, 0x2550, 0x25A0, 0x25B2, 0x25B6, 0x25CB, 0x2605,
    0x2713, 0x3001, 0x3002, 0x3010, 0x3011,
    0xFF01, 0xFF08, 0xFF09, 0xFF0C, 0xFF1A, 0xFF1F,
]

all_cps = set(ascii_cps)
for e in extra:
    all_cps.add(e)
for c in sorted_chars:
    all_cps.add(ord(c))

sorted_all = sorted(all_cps)

# ── 1) Write human-readable .txt ──
txt_path = os.path.join(os.path.dirname(__file__) or '.', 'font_codepoints.txt')
with open(txt_path, 'w', encoding='utf-8') as out:
    out.write('Total unique CJK chars: {}\n'.format(total))
    out.write('Total codepoints (with ASCII+symbols): {}\n\n'.format(len(sorted_all)))
    for i in range(0, len(sorted_all), 20):
        group = sorted_all[i:i+20]
        line = ', '.join('0x{:04X}'.format(cp) for cp in group)
        if i + 20 < len(sorted_all):
            out.write('    ' + line + ',\n')
        else:
            out.write('    ' + line + '\n')
print('OK: wrote {} codepoints to {}'.format(len(sorted_all), txt_path))

# ── 2) Write C++ header ──
hdr_path = os.path.join(os.path.dirname(__file__) or '.',
                        os.pardir, 'src', 'core', 'font_codepoints.h')
with open(hdr_path, 'w', encoding='utf-8') as out:
    out.write('#pragma once\n')
    out.write('// ═══════════════════════════════════════════════════════\n')
    out.write('// Auto-generated by tools/extract_chars.py\n')
    out.write('// Total unique CJK chars: {}  |  Total codepoints: {}\n'.format(total, len(sorted_all)))
    out.write('// ═══════════════════════════════════════════════════════\n')
    out.write('// Re-generate: py tools/extract_chars.py\n\n')
    out.write('static const int FONT_CP_COUNT = {};\n\n'.format(len(sorted_all)))
    out.write('static const int FONT_CP_DATA[] = {\n')
    for i in range(0, len(sorted_all), 20):
        group = sorted_all[i:i+20]
        line = ', '.join('0x{:04X}'.format(cp) for cp in group)
        if i + 20 < len(sorted_all):
            out.write('    {},\n'.format(line))
        else:
            out.write('    {}\n'.format(line))
    out.write('};\n')
print('OK: wrote {} codepoints to {}'.format(len(sorted_all), hdr_path))
