#pragma once
#include <array>
#include <string>

// ============================================================
// F15.3: PlayerHabitProfile — compact player style summary
// Generated from PlayerAction stream by PlayerBehaviorAnalyzer.
// Read by MirrorAgent to adapt Boss strategy.
// ============================================================

enum class PlayerStyle { AGGRESSIVE, DEFENSIVE, SNIPER, MAGE, BALANCED };

struct PlayerHabitProfile {
    // ── Combat rhythm ──
    float attack_frequency = 0.0f;   // attacks per second
    float skill_frequency  = 0.0f;   // skills per second
    float dodge_rate       = 0.0f;   // 0.0 = never, 1.0 = constant
    float aggression_score = 0.0f;   // 0.0=passive, 1.0=hyper-aggressive

    // ── Skill preference (0=slash, 1=fireball, 2=self_heal, 3=the_world) ──
    std::array<float, 4> skill_preference = {};

    // ── Movement habits ──
    float left_bias  = 0.5f;         // 0.0=all left, 1.0=all right
    float retreat_rate = 0.0f;       // fraction of moves going away from enemy
    float average_distance = 0.0f;   // preferred combat distance (pixels)

    // ── Survival ──
    float avg_damage_taken = 0.0f;   // per floor
    float heal_frequency   = 0.0f;   // heals per second

    // ── Classification ──
    PlayerStyle style = PlayerStyle::BALANCED;
    int    total_actions = 0;

    // ── Counter strategy hints (generated by analyzer) ──
    bool   predict_attack_heavy  = false;  // >70% attack = bait and punish
    bool   predict_skill_spam    = false;  // >60% skill uses on one skill
    int    predicted_fav_skill   = -1;     // -1=none, 0-3=skill index
    bool   predict_low_dodge     = false;  // <10% dodge = pressure close
    bool   predict_panic_heal    = false;  // heals at high HP = waste, punish during heal
    float  hp_counter_threshold  = 35.0f;  // HP% where player usually heals

    // ── M5: 条件维度 (从方向/受击上下文提取的真实习惯) ──
    // 被打后 1s 内的反击占比: >0.6 = 硬刚反击型, <0.3 = 被打就怂/后撤型
    float  fight_back_rate      = 0.0f;    // 受击窗口内攻击+技能动作 / 受击总数
    // 朝向稳定度: 主朝向占比 0.25~1.0 — 高=单向癖/退避轴可预测, 低=四面转/难以封锁
    float  face_enemy_rate      = 0.5f;
    // 攻击节奏方差: 相邻攻击间隔 stddev (秒) — 小=固定连段, 大=乱节奏难猜
    float  attack_rhythm_var    = 0.0f;

    const char* style_name() const;
    const char* counter_strategy_text() const;
};
